### PR TITLE
fix: storybook mdx files

### PR DESCRIPTION
**Pull request by Manukyanq**
On main branch [guidebook page](https://react-chessboard.vercel.app/?path=/docs/guidebook-stockfish-integration--page) written in MDX format has been broken. The problem is some uncertain dependency update conflict and the solution I found here: 

https://github.com/storybookjs/storybook/issues/18094#issuecomment-1112883092

### CODE REVIEW

**Comment by Manukyanq** [comment]
@Clariity please share buid logs on Vercel, locally all build scripts work fine for me 🥹

**Comment by Clariity** [comment]
Running "install" command: `npm install`...
--
19:51:30.079 | npm ERR! code ERESOLVE
19:51:30.224 | npm ERR! ERESOLVE could not resolve
19:51:30.224 | npm ERR!
19:51:30.224 | npm ERR! While resolving: @mdx-js/react@1.6.22
19:51:30.224 | npm ERR! Found: react@18.2.0
19:51:30.224 | npm ERR! node_modules/react
19:51:30.225 | npm ERR!   dev react@"^18.2.0" from the root project
19:51:30.225 | npm ERR!   peer react@">= 16.8.6" from @design-systems/utils@2.12.0
19:51:30.225 | npm ERR!   node_modules/@design-systems/utils
19:51:30.225 | npm ERR!     @design-systems/utils@"2.12.0" from @devtools-ds/themes@1.2.1
19:51:30.225 | npm ERR!     node_modules/@devtools-ds/themes
19:51:30.225 | npm ERR!       @devtools-ds/themes@"^1.2.1" from @devtools-ds/object-inspector@1.2.1
19:51:30.225 | npm ERR!       node_modules/@devtools-ds/object-inspector
19:51:30.225 | npm ERR!         @devtools-ds/object-inspector@"^1.1.2" from @storybook/addon-interactions@6.5.15
19:51:30.225 | npm ERR!         node_modules/@storybook/addon-interactions
19:51:30.225 | npm ERR!       1 more (@devtools-ds/tree)
19:51:30.225 | npm ERR!   122 more (@devtools-ds/object-inspector, @devtools-ds/themes, ...)
19:51:30.225 | npm ERR!
19:51:30.225 | npm ERR! Could not resolve dependency:
19:51:30.225 | npm ERR! peer react@"^16.13.1 \|\| ^17.0.0" from @mdx-js/react@1.6.22
19:51:30.225 | npm ERR! node_modules/@mdx-js/react
19:51:30.225 | npm ERR!   dev @mdx-js/react@"^1.6.22" from the root project
19:51:30.225 | npm ERR!   @mdx-js/react@"^1.6.22" from @storybook/addon-docs@6.5.16
19:51:30.225 | npm ERR!   node_modules/@storybook/addon-docs
19:51:30.225 | npm ERR!     @storybook/addon-docs@"6.5.16" from @storybook/addon-essentials@6.5.16
19:51:30.225 | npm ERR!     node_modules/@storybook/addon-essentials
19:51:30.225 | npm ERR!       dev @storybook/addon-essentials@"^6.5.15" from the root project
19:51:30.225 | npm ERR!
19:51:30.225 | npm ERR! Conflicting peer dependency: react@17.0.2
19:51:30.225 | npm ERR! node_modules/react
19:51:30.225 | npm ERR!   peer react@"^16.13.1 \|\| ^17.0.0" from @mdx-js/react@1.6.22
19:51:30.225 | npm ERR!   node_modules/@mdx-js/react
19:51:30.225 | npm ERR!     dev @mdx-js/react@"^1.6.22" from the root project
19:51:30.225 | npm ERR!     @mdx-js/react@"^1.6.22" from @storybook/addon-docs@6.5.16
19:51:30.225 | npm ERR!     node_modules/@storybook/addon-docs
19:51:30.225 | npm ERR!       @storybook/addon-docs@"6.5.16" from @storybook/addon-essentials@6.5.16
19:51:30.225 | npm ERR!       node_modules/@storybook/addon-essentials
19:51:30.226 | npm ERR!         dev @storybook/addon-essentials@"^6.5.15" from the root project
19:51:30.226 | npm ERR!
19:51:30.226 | npm ERR! Fix the upstream dependency conflict, or retry
19:51:30.226 | npm ERR! this command with --force, or --legacy-peer-deps
19:51:30.226 | npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
19:51:30.226 | npm ERR!
19:51:30.226 | npm ERR! See /vercel/.npm/eresolve-report.txt for a full report.
19:51:30.226 |  
19:51:30.226 | npm ERR! A complete log of this run can be found in:
19:51:30.226 | npm ERR!     /vercel/.npm/_logs/2024-05-19T18_51_23_079Z-debug-0.log
19:51:30.254 | Error: Command "npm install" exited with 1


@Manukyanq here you go

**Comment by Clariity** [comment]
probably worth just upgrading storybook to latest

**Comment by Manukyanq** [comment]
Thanks! I will try

**Comment by Clariity** [comment]
Updated and fixed on main

**Pull request closed without merging**
