### PR TITLE
Adds data props for Square elements

### PR DESCRIPTION
**Pull request by benjaminknox**
## What

A nice thing about chessboardjsx is that they have handles on elements for testing, this adds a few that would be great to have!

## Details
- On the Square adds these two data props:
   - `data-square-color={squareColor}`
   - `data-square={square}`

### CODE REVIEW

**Comment by Clariity** [comment]
love this, thanks for the contribution

**Comment by benjaminknox** [comment]
I pulled the NPM package and it didn't have the correct build, did I need to include the build in the repo for it to work correctly?

https://github.com/Clariity/react-chessboard/pull/8

**Comment by Clariity** [comment]
it was my mistake, i didn't add the build to the npm publish, ill correct it now, cheers for spotting it

**Comment by benjaminknox** [comment]
👍🏻 No problem, thank you for the quick response 😄

**Pull request merged**
