### PR TITLE
Added typescript types

### PR DESCRIPTION
**Pull request by Trunkelis**
These types should be accurate.

### CODE REVIEW

**Comment by Clariity** [comment]
Thanks for creating a type declaration file for the project, I'm on holiday currently but I'll give this a look over when I'm back next week

**Comment by Clariity** [comment]
Had a quick look, type declaration file itself looks great and will be really helpful to add typescript support to the package.

I'm not sure it will package correctly however, as the types field is pointing to ./index.d.ts when it should be packaged into dist/index.d.ts. So I think that needs to be changed and the Rollup file will need some configuration too in order to bundle the new types file, are you okay adding those changes please?

**Comment by Trunkelis** [comment]
@Clariity  Yeah, I can do it when I'm free.

**Comment by Trunkelis** [comment]
@Clariity I searched a bit and rollup doesn't seem to have type bundling by default, so I needed to install this plugin [rollup-plugin-dts](https://github.com/Swatinem/rollup-plugin-dts)

**Pull request merged**
